name: Preprocessing Automation

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  preprocess:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./preprocessing
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12.7

      - name: Install dependencies
        run: pip install pandas scikit-learn

      - name: Run automate_Rizal.py
        run: python automate_Rizal.py

      - name: Show output
        run: ls -l

      # Jika ingin hasil iris_preprocessing.csv di-push ke repo otomatis:
      - name: Commit changes
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'actions@github.com'
          git add penguins_preprocessing.csv
          git commit -m "Auto update penguins_preprocessing.csv" || echo "No changes to commit"
          git push || echo "No changes to push"
